FROM microsoft/aspnetcore-build:2.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["catalog/catalog.csproj", "catalog/"]

RUN dotnet restore "catalog/catalog.csproj"
COPY . .
WORKDIR "/src/catalog"
RUN dotnet build --no-restore "catalog.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]